### ISSUE TITLE
Transfer to upstream

### ISSUE THREAD

**Issue by nedrichards** [flathub/net.xmind.ZEN#11]
The upstream XMind developers would like to take over XMind on flathub. https://github.com/flathub/flathub/pull/2913#issuecomment-1067635749 As a longstanding matter of flathub policy we're delighted that this is happening. As part of this they would like to change app-id, EOL this app and redirect users to the new app-id which is net.xmind.XMind. This is just giving you a heads up that this will happen. If you want to do the EOL and redirect yourself then that would save the flathub admins some work and would be appreciated ;-) otherwise we'll do this and archive the repo within the next few days.

@barthalion @muelli FYI

**Comment by muelli** [comment]
https://github.com/flathub/net.xmind.ZEN/commit/f1b6a09de84428fe554e2cd5d2840be8cb021d53
